name = "smart-form-assistant"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "forms_db"
database_id = "placeholder-will-be-set-after-creation"

[[kv_namespaces]]
binding = "SESSIONS"
id = "placeholder-will-be-set-after-creation"

[vars]
NODE_ENV = "production"

